Added full Orcid id to display #5
ulsdevteam/pkp-editorialBio pull request #8
Opened 2023-10-06 14:46 UTC by trp89

Added functionality to include the full orcid id and icon for a profile, adjusting surrounding contents of the biography page.

2023-10-06 15:20 UTC, ctgraham requested changes
Please see changes requested here.  Thanks!

2023-10-06 15:20 UTC, ctgraham commented on EditorialBioHandler.php
> +		$orcidIcon = $orcidProfile->getIcon();
What happens here if the orcidProfile plugin is not installed or not enabled?  There needs to be some conditional logic here.

2023-10-06 15:20 UTC, ctgraham commented on templates/frontend/pages/aboutEditorialTeamBio.tpl
> + * @uses $templateEditor User The editor with a bio to show
We used the rename of `$editor` to `$templateEditor` to illustrate the difference in the controller and template variables, but we don't to persist the change.  Let's revert this to keep the noise down in the diff.

2023-10-06 15:20 UTC, ctgraham commented on templates/frontend/pages/aboutEditorialTeamBio.tpl
> +	<div style="display:flex;" class="orcidContent">
CSS should not be added inline, as it cannot be overridden.  Use classes to target your elements, and a stylesheet include to style the classed elements.  You can see an example of adding a stylesheet here:
https://github.com/pkp/orcidProfile/blob/c3375e3809468c53a104021d397f44daabdf7c13/OrcidProfilePlugin.php#L547-L579

2023-10-06 15:20 UTC, ctgraham commented on templates/frontend/pages/aboutEditorialTeamBio.tpl
> +			<a style="font-size:24px;"href = {$templateEditor->getData('orcid')}> {$templateEditor->getData('orcid')} </a>
The `href` attribute is abutted to the closing quote of the `style` attribute, and is missing any quotes of its own.

2023-10-09 20:13 UTC, ctgraham requested changes
Some style requests.

2023-10-09 20:13 UTC, ctgraham commented on EditorialBioPlugin.php
> +	{
This brace doesn't match surrounding style.

2023-10-09 20:13 UTC, ctgraham commented on EditorialBioHandler.php
> +		if ($orcidProfile){
The spacing between the close paren and brace doesn't match surrounding style.

2023-10-09 20:13 UTC, ctgraham commented on EditorialBioHandler.php
> +			if($orcidProfile) {
The space between the `if` and open paran doesn't match surrounding style.

2023-10-09 20:13 UTC, ctgraham commented on css/editorialBio.css
> +.orcidContent{
Please add a space between each definition and opening curly brace.

2023-10-09 20:13 UTC, ctgraham commented on css/editorialBio.css
> +.orcidIcon{
These names are generic enough to be potentially used by someone else.  You can easily disambiguate our use case by specifying that they need to live within an `div.editorialTeamBioContent`.  See https://www.w3schools.com/css/default.asp for good CSS guide (e.g. our discussion on `.classes` vs. `#identifier`.

2023-10-09 20:13 UTC, ctgraham commented on css/editorialBio.css
> +    width:24px;
ORCID guidelines state:
* Scale the iD icon to match the line height of the surrounding text but go no smaller than 16×16.
* Allow for at least 50% buffer space around the icon. For the 16×16 pixel icon, this translates into a four-pixel margin on each side of the icon.

A better implementation could be:
```
  width: 1em;
  height: 1em;
  min-width: 16px;
  min-height: 16px;
  margin-left: .25em;
  margin-right: .25em;
```

2023-10-09 20:13 UTC, ctgraham commented on css/editorialBio.css
> +    font-size:24px;
Fonts generally should not be bound to specific pixel measurements.  This inhibits dynamic resizing, for example in the case of individuals with low vision.  Rather, text size is based on `em`s.  Here, I'm unconvinced of the need to increase the text size, but if we did, I think we would want it more subtle, like 1.2em.

2023-10-10 17:41 UTC, ctgraham requested changes
The restructuring of the classing looks off to me.

2023-10-10 17:41 UTC, ctgraham commented on templates/frontend/pages/aboutEditorialTeamBio.tpl
> +<div class="editorialTeamBioContent">
Why was the classing of `page page_about_editorial_team_bio` removed, and why was the classing of `editorialTeamBioContent` moved from the div after the headers to now contain the headers?

The general HTML structure should remain similar to other public facing pages, e.g.:
https://github.com/pkp/pkp-lib/blob/6b70a88a7d3170af23abfeea86486960bd8365b1/templates/frontend/pages/about.tpl#L15-L23

2023-10-10 17:55 UTC, trp89 commented on templates/frontend/pages/aboutEditorialTeamBio.tpl
> +<div class="editorialTeamBioContent">
When I was testing spacing, the child class of editorialTeamBioContent  required a div with editorialTeamBioContent enveloping it so the spacing would appear properly on the page. I changed that div because it fit those criteria I was testing.  I will restore that line and just add a separate div.

2023-10-10 18:07 UTC, ctgraham requested changes
Your primary goal in structuring the template file is to layout the elements such that they flow naturally in a meaningful hierarchy.  Some things, like the specific CSS rules around rendering the ORCID icon, text and link, make sense living in this plugin, but you can also defer many styling specifics to the larger theme and designer.

For example, when adding a new image, be sure to class it such that a designer could choose whether they want it to appear above the biography text, or in line with the biography text.

When working with spacing, semantically choose when a section is a `<p>` paragraph, or a arbitrary `<div>` division, and refer to the larger theme for any classes which are appropriate (e.g. `div.page`, but if nothing already exists which is appropriate, give the designer a new class to hook into.

2023-10-10 18:07 UTC, ctgraham commented on templates/frontend/pages/aboutEditorialTeamBio.tpl
> +	<div>
You probably want to restore the classing here (principle: don't change something unless it needs to be changed), and insert the new ORCID content inside this div (principle: associate like content).

2023-10-10 18:07 UTC, ctgraham commented on templates/frontend/pages/aboutEditorialTeamBio.tpl
> +		{$editor->getLocalizedData('biography')|strip_unsafe_html}<br>
The addition of a `<br />` here is suspect.  If there are spacing issues, the correct way to deal with this is adding CSS for margin, padding, etc.

2023-10-12 13:28 UTC, ctgraham approved these changes

2023-10-12 13:41 UTC, merged